language: ruby
script: "bundle exec rake spec"
notifications:
  email:
    recipients:
      - softwaredev-notify@wwwh.com
    on_success: never
    on_failure: always
rvm:
  - 2.1.3
  - 2.2.0
  - 2.3.1
  - jruby-19mode
before_install:
  - gem update bundler
